### PR TITLE
Add node 10 support to travici

### PR DESCRIPTION
**Pull request by DrFaust92**
Added node 10 to TravisCI yaml

### CODE REVIEW

**Comment by DrFaust92** [comment]
closes #34

**Comment by DrFaust92** [comment]
@lirantal , any reason the .travis.yml uses an (explicit) old yarn version installation? the node image already comes bundled with yarn.

**Comment by lirantal** [comment]
Looks great @DrFaust92, thanks for chiming in on this ✨
No reason for the explicit yarn install, we could definitely clean-up the travis file with regards to this.

Currently traveling but I'll land this PR in soon enough.

**Review by lirantal — APPROVED** [review]

**Comment by lirantal** [comment]
@DrFaust92 thanks again.
happy to merge another PR to clean-up the yarn part if you're up for it.

**Pull request merged**
